{
  "hash": "6ed99703700c8c9463e2f4ebca5e76ee",
  "result": {
    "engine": "knitr",
    "markdown": "---\nsidebar: false\ntitle: \"ThSQCA for beginners, part 2: the four sweeps and how to choose a range\"\nauthor: \"Yuki Toyoda\"\nimage: thumbnail.png\ndate: \"2026-10-08\"\ncategories: [R, ThSQCA, tutorial]\ndescription: \"Sweep the outcome, one condition, several conditions, or both. We run all four sweeps on a practice data set and discuss how to choose a threshold range you can defend.\"\n---\n\nIn [part 1](../thsqca-beginners-1/index.html) we ran an outcome threshold sweep and read its result. ThSQCA has four sweep functions in total. This post runs all four on the same practice data, and ends with practical advice on choosing the range of thresholds.\n\n## The four sweeps at a glance\n\n| Question | Function | What varies | What stays fixed |\n|---|---|---|---|\n| How does the solution change as the target level of the outcome rises? | `otSweep()` | the outcome threshold | all condition thresholds |\n| How sensitive is it to one condition's definition of \"high\"? | `ctSweepS()` | one condition threshold | the outcome and the other conditions |\n| What if several conditions' definitions change together? | `ctSweepM()` | several condition thresholds (a grid) | the outcome threshold |\n| What if the target level and the conditions' definitions both change? | `dtSweep()` | the outcome and the conditions | nothing |\n\n## Setup: the same practice data as part 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ThSQCA)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Practice data (identical to part 1)\"}\nmake_demo_data <- function(n = 400, seed = 2026) {\n  set.seed(seed)\n  clip <- function(x) pmin(10, pmax(0, round(x)))\n  QUA <- clip(rnorm(n, 6, 2))\n  SER <- clip(rnorm(n, 6, 2))\n  ENV <- clip(rnorm(n, 6, 2))\n  core <- pmax(pmin(QUA, SER), pmin(QUA, ENV) - 1)\n  LOY  <- clip(core + rnorm(n, 0, 0.7))\n  data.frame(LOY, QUA, SER, ENV)\n}\n\ndemo <- make_demo_data()\n```\n:::\n\n\nRemember the story behind the data: loyalty (`LOY`) is high when quality (`QUA`) and service (`SER`) are both high, or, a little less strongly, when quality and the store environment (`ENV`) are both high.\n\n## Sweep 1: one condition with `ctSweepS()`\n\nSuppose you are unsure where to draw the line for \"high service delivery\". Is 6 high enough? 7? 9? Fix the outcome at `LOY >= 7`, fix the other conditions at 7, and sweep the threshold of `SER` from 5 to 9.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_cts <- ctSweepS(\n  dat          = demo,\n  outcome      = \"LOY\",\n  conditions   = c(\"QUA\", \"SER\", \"ENV\"),\n  sweep_var    = \"SER\",\n  sweep_range  = 5:9,\n  thrY         = 7,\n  thrX_default = 7\n)\n\nsummary(res_cts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCTS (single) Summary\n==================== \n\nAnalysis Parameters:\n  Outcome: LOY \n  Conditions: QUA, SER, ENV \n  Consistency cutoff: 0.8 \n  Frequency cutoff: 1 \n\nResults by Threshold:\n\n threshold   expression inclS  covS n_solutions\n         5  No solution    NA    NA           0\n         6  No solution    NA    NA           0\n         7      QUA*SER 0.894 0.656           1\n         8      QUA*SER 0.909 0.333           1\n         9 QUA*SER*~ENV 0.917 0.122           1\n```\n\n\n:::\n:::\n\n\nThe new arguments are `sweep_var` (the condition whose threshold is swept), `thrY` (the fixed outcome threshold), and `thrX_default` (the fixed threshold for all other conditions).\n\nReading the table from top to bottom: when \"high service\" is defined as 5 or 6, there is no solution, because the definition is so loose that the group of \"highly served\" customers is no longer reliably loyal. At 7 and 8 the solution is `QUA*SER`. At 9 the solution gains a third element, `QUA*SER*~ENV`, and coverage falls sharply, from 0.656 at 7 to 0.122 at 9. You can see why by counting how many customers are behind the strictest definition:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(demo$QUA >= 7 & demo$SER >= 9)                 # customers high on both quality and service\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(demo$QUA >= 7 & demo$SER >= 9 & demo$ENV < 7)  # customers satisfying the solution QUA*SER*~ENV\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12\n```\n\n\n:::\n:::\n\n\nOf the 400 customers, 16 are high on both quality and service, and only 12 of them also have a store-environment score below 7, which is what the solution `QUA*SER*~ENV` requires. The result there rests on very few cases. This is a useful habit: when a solution appears only at the edge of the grid, check how many cases are behind it.\n\n## Sweep 2: several conditions with `ctSweepM()`\n\nNow let the thresholds of all three conditions vary at once: each of `QUA`, `SER`, and `ENV` is tried at 6, 7, and 8. That is 3 x 3 x 3 = 27 combinations. The outcome stays at `LOY >= 7`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_mcts <- ctSweepM(\n  dat        = demo,\n  outcome    = \"LOY\",\n  conditions = c(\"QUA\", \"SER\", \"ENV\"),\n  sweep_list = list(QUA = 6:8, SER = 6:8, ENV = 6:8),\n  thrY       = 7\n)\n```\n:::\n\n\nThe output has 27 rows. To keep it readable, show only the combinations that produced a solution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab <- res_mcts$summary\ntab[tab$n_solutions > 0, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   combo_id           threshold                  expression     inclS      covS\n5         5 QUA=7, SER=7, ENV=6                     QUA*SER 0.8939394 0.6555556\n6         6 QUA=8, SER=7, ENV=6                     QUA*SER 0.9189189 0.3777778\n8         8 QUA=7, SER=8, ENV=6                     QUA*SER 0.9090909 0.3333333\n9         9 QUA=8, SER=8, ENV=6                     QUA*SER 0.9047619 0.2111111\n12       12 QUA=8, SER=6, ENV=7                QUA*SER*~ENV 0.8000000 0.3111111\n14       14 QUA=7, SER=7, ENV=7                     QUA*SER 0.8939394 0.6555556\n15       15 QUA=8, SER=7, ENV=7                QUA*SER*~ENV 1.0000000 0.3000000\n17       17 QUA=7, SER=8, ENV=7                     QUA*SER 0.9090909 0.3333333\n18       18 QUA=8, SER=8, ENV=7                QUA*SER*~ENV 1.0000000 0.1888889\n21       21 QUA=8, SER=6, ENV=8                     QUA*ENV 0.8888889 0.1777778\n23       23 QUA=7, SER=7, ENV=8                     QUA*SER 0.8939394 0.6555556\n24       24 QUA=8, SER=7, ENV=8           QUA*SER + QUA*ENV 0.9200000 0.5111111\n26       26 QUA=7, SER=8, ENV=8                     QUA*SER 0.9090909 0.3333333\n27       27 QUA=8, SER=8, ENV=8 QUA*SER*~ENV + QUA*~SER*ENV 0.9393939 0.3444444\n   n_solutions\n5            1\n6            1\n8            1\n9            1\n12           1\n14           1\n15           1\n17           1\n18           1\n21           1\n23           1\n24           1\n26           1\n27           1\n```\n\n\n:::\n:::\n\n\nSome patterns to look for:\n\n- Fourteen of the 27 combinations have a solution. In every combination where \"high quality\" is defined as 6, there is no solution at all.\n- With `QUA` at 7 and `SER` at 7 or 8, the solution is `QUA*SER` no matter which threshold is used for `ENV`. This is a **stable region**.\n- With `QUA` at 8, the solution depends on `ENV` (and on `SER`). With `ENV` at 6 it is `QUA*SER` (when `SER` is 7 or 8). With `ENV` at 7 it is `QUA*SER*~ENV`. With `ENV` at 8 it varies, from `QUA*ENV` alone to two-path solutions such as `QUA*SER + QUA*ENV`. When \"high quality\" is defined strictly, the definition of the store environment starts to matter.\n\nThe grid shows both where a conclusion is robust and where it is fragile, which a single analysis cannot.\n\n## Sweep 3: the outcome and the conditions together with `dtSweep()`\n\nThe dual threshold sweep combines the two ideas: it varies the target level of the outcome and the conditions' definitions at the same time. Here we use 3 outcome thresholds (6, 7, 8) and 8 condition combinations (`QUA`, `SER`, `ENV` each at 6 or 7), so 24 cells.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_dts <- dtSweep(\n  dat           = demo,\n  outcome       = \"LOY\",\n  conditions    = c(\"QUA\", \"SER\", \"ENV\"),\n  sweep_list_X  = list(QUA = 6:7, SER = 6:7, ENV = 6:7),\n  sweep_range_Y = 6:8\n)\n\nres_dts$summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   combo_id thrY                thrX        expression     inclS      covS\n1         1    6 QUA=6, SER=6, ENV=6           QUA*SER 0.8630137 0.7118644\n2         1    7 QUA=6, SER=6, ENV=6       No solution        NA        NA\n3         1    8 QUA=6, SER=6, ENV=6       No solution        NA        NA\n4         2    6 QUA=7, SER=6, ENV=6           QUA*SER 0.9215686 0.5310734\n5         2    7 QUA=7, SER=6, ENV=6       No solution        NA        NA\n6         2    8 QUA=7, SER=6, ENV=6       No solution        NA        NA\n7         3    6 QUA=6, SER=7, ENV=6           QUA*SER 0.8932039 0.5197740\n8         3    7 QUA=6, SER=7, ENV=6       No solution        NA        NA\n9         3    8 QUA=6, SER=7, ENV=6       No solution        NA        NA\n10        4    6 QUA=7, SER=7, ENV=6           QUA*SER 0.9848485 0.3672316\n11        4    7 QUA=7, SER=7, ENV=6           QUA*SER 0.8939394 0.6555556\n12        4    8 QUA=7, SER=7, ENV=6       No solution        NA        NA\n13        5    6 QUA=6, SER=6, ENV=7           QUA*SER 0.8630137 0.7118644\n14        5    7 QUA=6, SER=6, ENV=7       No solution        NA        NA\n15        5    8 QUA=6, SER=6, ENV=7       No solution        NA        NA\n16        6    6 QUA=7, SER=6, ENV=7 QUA*SER + QUA*ENV 0.9076923 0.6666667\n17        6    7 QUA=7, SER=6, ENV=7       No solution        NA        NA\n18        6    8 QUA=7, SER=6, ENV=7       No solution        NA        NA\n19        7    6 QUA=6, SER=7, ENV=7           QUA*SER 0.8932039 0.5197740\n20        7    7 QUA=6, SER=7, ENV=7       No solution        NA        NA\n21        7    8 QUA=6, SER=7, ENV=7       No solution        NA        NA\n22        8    6 QUA=7, SER=7, ENV=7 QUA*SER + QUA*ENV 0.9259259 0.5649718\n23        8    7 QUA=7, SER=7, ENV=7           QUA*SER 0.8939394 0.6555556\n24        8    8 QUA=7, SER=7, ENV=7       No solution        NA        NA\n   n_solutions\n1            1\n2            0\n3            0\n4            1\n5            0\n6            0\n7            1\n8            0\n9            0\n10           1\n11           1\n12           0\n13           1\n14           0\n15           0\n16           1\n17           0\n18           0\n19           1\n20           0\n21           0\n22           1\n23           1\n24           0\n```\n\n\n:::\n:::\n\n\nReading it: at `LOY >= 6`, every one of the 8 condition definitions gives a solution, usually `QUA*SER`, and sometimes `QUA*SER + QUA*ENV`. At `LOY >= 7`, only two definitions still give a solution, the ones where `QUA` and `SER` are both at 7. At `LOY >= 8`, none do. In this data set, raising the target level is the strongest driver of change.\n\n## How big is a sweep?\n\nEvery cell is a full QCA analysis, so the number of cells matters for run time and for how readable the results are.\n\n| Function | Number of analyses | Example |\n|---|---|---|\n| `otSweep()` | one per outcome threshold | 5 thresholds = 5 |\n| `ctSweepS()` | one per threshold of the swept condition | 5 thresholds = 5 |\n| `ctSweepM()` | the product of the candidate counts | 3 x 3 x 3 = 27 |\n| `dtSweep()` | outcome thresholds x condition grid | 3 x (3 x 3 x 3) = 81 |\n\n## Choosing a range you can defend\n\nA sweep is easy to run, which is exactly why it needs discipline. Trying many thresholds and reporting only the convenient ones would add researcher degrees of freedom instead of removing them. Some rules of thumb:\n\n1. **Decide the range before you look at the results.** Base it on what the scale means, on theory, and on practical targets (for example \"acceptable\", \"good\", \"very good\").\n2. **Include your baseline.** The threshold you would have used in an ordinary analysis should be inside the grid, so readers can compare.\n3. **Avoid the neutral zone.** On a 0 to 10 scale, scores around the midpoint do not clearly mean \"high\" for anyone, so ranges usually start above it.\n4. **Keep the grid small enough to read.** A few meaningful values per variable are better than every possible value.\n5. **Check the case counts at the edges.** Cells at the extremes of the grid often rest on very few cases.\n6. **Report the whole grid.** Show the stable and the unstable regions, not only the cells that support your story.\n\n## What comes next\n\nIn [part 3](../thsqca-beginners-3/index.html) we look at the three solution types (complex, parsimonious, and intermediate) and at what to do when a cell has more than one minimal solution.\n\n*Software used: R 4.6.1, QCA 3.25.5, and ThSQCA 2.0.9.*\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}